# Generated by Django 5.1.6 on 2025-03-04 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(11, 28, 59, 385254), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 4, 11, 33, 59, 384257, tzinfo=datetime.timezone.utc)),
        ),
    ]
