# Generated by Django 5.1.6 on 2025-03-22 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(15, 22, 54, 577265), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 22, 15, 27, 54, 576262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recommendedexercise',
            name='datetime_recommended',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 22, 54, 578258, tzinfo=datetime.timezone.utc)),
        ),
    ]
