# Generated by Django 5.1.6 on 2025-02-14 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_rename_user_id_otp_user_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 14, 0, 38, 5, 832644, tzinfo=datetime.timezone.utc)),
        ),
    ]
