# Generated by Django 5.1.6 on 2025-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_consumable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
