# Generated by Django 5.1.6 on 2025-04-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_loggedroutine'),
        ('onboarding', '0003_alter_consumable_name'),
    ]

    operations = [
    ]
