# Generated by Django 5.1.6 on 2025-02-17 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verified',
            field=models.BooleanField(db_comment='Whether the OTP for the user has been verified. Good for preventing repeat entries and also ensuring user is secure.', default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 17, 2, 56, 32, 69822, tzinfo=datetime.timezone.utc)),
        ),
    ]
