# Generated by Django 5.1.6 on 2025-02-17 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 17, 19, 25, 52, 635009, tzinfo=datetime.timezone.utc)),
        ),
    ]
