# Generated by Django 5.1.6 on 2025-02-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_otp_verified_alter_otp_expiry_time'),
        ('onboarding', '0010_alter_otp_expiry_time'),
    ]

    operations = [
    ]
