# Generated by Django 5.1.6 on 2025-02-25 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_merge_20250220_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(db_comment='The name of the exercise', default='', max_length=80)),
                ('ex_type', models.CharField(db_comment='Type of exercise, Cardio, Muscle etc', default='', max_length=100)),
                ('ex_body_area', models.CharField(db_comment='What body part the exercise is working on: Legs, back, chest etc', default='', max_length=15)),
                ('equiptment_needed', models.CharField(db_comment='Equptment needed for exercise', default='none', max_length=80)),
                ('ex_target_muscle', models.CharField(db_comment='Target Muscle - can be null for cardio', max_length=20, null=True)),
                ('ex_secondary_muscle_1', models.CharField(db_comment='Secondary muscle targeted', max_length=30, null=True)),
                ('ex_secondary_muscle_2', models.CharField(db_comment='Other Secondary muscle targeted', max_length=30, null=True))
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 18, 37, 8, 887126, tzinfo=datetime.timezone.utc)),
        ),
    ]
