# Generated by Django 5.1.6 on 2025-02-25 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ex_body_area',
            field=models.CharField(choices=[('arms', 'Arms'), ('back', 'Back'), ('legs', 'Legs'), ('core', 'Core'), ('chest', 'Chest'), ('shoulder', 'Shoulder'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('neck', 'Neck')], db_comment='What body part the exercise is working on: Legs, back, chest etc', max_length=15),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_secondary_muscle',
            field=models.CharField(choices=[('Arms', [('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms')]), ('Back', [('lats', 'Lats'), ('lower_back', 'Lower Back'), ('traps', 'Traps'), ('upper_back', 'Upper Back')]), ('Legs', [('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quadriceps', 'Quadriceps'), ('adductors', 'Adductors'), ('glutes', 'Glutes')]), ('Core', [('abs', 'Abdominals'), ('abductors', 'Abductors')]), ('neck', [('levator_scapulae', 'Levator Scapulae')]), ('shoulders', [('delts', 'Delts')]), ('chest', [('pecs', 'Pectorals'), ('serratus anterior', 'Serratus Anterior')])], db_comment='Secondary muscle targeted', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_target_muscle',
            field=models.CharField(choices=[('Arms', [('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms')]), ('Back', [('lats', 'Lats'), ('lower_back', 'Lower Back'), ('traps', 'Traps'), ('upper_back', 'Upper Back')]), ('Legs', [('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quadriceps', 'Quadriceps'), ('adductors', 'Adductors'), ('glutes', 'Glutes')]), ('Core', [('abs', 'Abdominals'), ('abductors', 'Abductors')]), ('neck', [('levator_scapulae', 'Levator Scapulae')]), ('shoulders', [('delts', 'Delts')]), ('chest', [('pecs', 'Pectorals'), ('serratus anterior', 'Serratus Anterior')])], db_comment='Target Muscle - can be null for cardio', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_type',
            field=models.CharField(choices=[('muscle', 'Muscle'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], db_comment='Type of exercise, Cardio, Muscle etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 18, 40, 10, 561427, tzinfo=datetime.timezone.utc)),
        ),
    ]
