# Generated by Django 5.1.6 on 2025-02-25 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_alter_exercise_ex_body_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 18, 57, 56, 833728, tzinfo=datetime.timezone.utc)),
        ),
    ]
