# Generated by Django 5.1.6 on 2025-02-25 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0020_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equiptment_needed',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_needed',
            field=models.CharField(db_comment='Equipment needed for exercise', default='none', max_length=80),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 22, 9, 25, 309688, tzinfo=datetime.timezone.utc)),
        ),
    ]
