# Generated by Django 5.1.6 on 2025-02-25 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_remove_exercise_equiptment_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 22, 12, 47, 597952, tzinfo=datetime.timezone.utc)),
        ),
    ]
