# Generated by Django 5.1.6 on 2025-02-25 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0022_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ex_secondary_muscle',
            field=models.CharField(choices=[('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('lats', 'Lats'), ('lower_back', 'Lower Back'), ('traps', 'Traps'), ('upper_back', 'Upper Back'), ('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quadriceps', 'Quadriceps'), ('adductors', 'Adductors'), ('glutes', 'Glutes'), ('abs', 'Abdominals'), ('abductors', 'Abductors'), ('levator_scapulae', 'Levator Scapulae'), ('delts', 'Delts'), ('pecs', 'Pectorals'), ('serratus terior', 'Serratus Anterior')], db_comment='Secondary muscle targeted', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_target_muscle',
            field=models.CharField(choices=[('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('lats', 'Lats'), ('lower_back', 'Lower Back'), ('traps', 'Traps'), ('upper_back', 'Upper Back'), ('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quadriceps', 'Quadriceps'), ('adductors', 'Adductors'), ('glutes', 'Glutes'), ('abs', 'Abdominals'), ('abductors', 'Abductors'), ('levator_scapulae', 'Levator Scapulae'), ('delts', 'Delts'), ('pecs', 'Pectorals'), ('serratus terior', 'Serratus Anterior')], db_comment='Target Muscle - can be null for cardio', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_type',
            field=models.CharField(choices=[('muscle', 'muscle'), ('cardio', 'cardio'), ('flexibility', 'flexibility')], db_comment='Type of exercise, Cardio, Muscle etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 22, 31, 7, 951377, tzinfo=datetime.timezone.utc)),
        ),
    ]
