# Generated by Django 5.1.6 on 2025-02-25 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0023_alter_exercise_ex_secondary_muscle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ex_id',
            field=models.IntegerField(db_comment='ID of each exercise', default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 25, 22, 46, 22, 9365, tzinfo=datetime.timezone.utc)),
        ),
    ]
