# Generated by Django 5.1.6 on 2025-02-26 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0024_exercise_ex_id_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='ex_id',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_body_area',
            field=models.CharField(db_comment='What body part the exercise is working on: Legs, back, chest etc', default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_secondary_muscle',
            field=models.CharField(db_comment='Secondary muscle targeted', default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_target_muscle',
            field=models.CharField(db_comment='Target Muscle - can be null for cardio', default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_type',
            field=models.CharField(db_comment='Type of exercise, Cardio, Muscle etc', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 0, 45, 11, 801259, tzinfo=datetime.timezone.utc)),
        ),
    ]
