# Generated by Django 5.1.6 on 2025-02-26 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0025_remove_exercise_ex_id_alter_exercise_ex_body_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 0, 53, 27, 317211, tzinfo=datetime.timezone.utc)),
        ),
    ]
