# Generated by Django 5.1.6 on 2025-02-26 17:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0029_alter_otp_expiry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 17, 49, 31, 579122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='LoggedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(default=datetime.date(2025, 2, 26))),
                ('time_logged', models.TimeField(default=datetime.time(17, 44, 31, 579122))),
                ('sets', models.PositiveSmallIntegerField(default=0)),
                ('reps', models.PositiveSmallIntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('distance_units', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], max_length=5)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('equipment_weight', models.JSONField(default=list)),
                ('equipment_weight_units', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], max_length=2)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
