# Generated by Django 5.1.6 on 2025-02-26 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0030_alter_otp_expiry_time_loggedexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(17, 57, 47, 987393)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 18, 2, 47, 987393, tzinfo=datetime.timezone.utc)),
        ),
    ]
