# Generated by Django 5.1.6 on 2025-02-26 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0033_alter_loggedexercise_time_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='date_logged',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 18, 3, 0, 441332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.datetime(2025, 2, 26, 18, 3, 0, 441332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 18, 8, 0, 441332, tzinfo=datetime.timezone.utc)),
        ),
    ]
