# Generated by Django 5.1.6 on 2025-02-26 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0036_alter_loggedexercise_date_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='date_logged',
            field=models.DateField(default=datetime.date(2025, 2, 26)),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(18, 6, 16, 942464)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 18, 11, 16, 940458, tzinfo=datetime.timezone.utc)),
        ),
    ]
