# Generated by Django 5.1.6 on 2025-02-26 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0037_alter_loggedexercise_date_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='distance',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='distance_units',
            field=models.CharField(choices=[('km', 'km'), ('mi', 'mi')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='equipment_weight',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='equipment_weight_units',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='reps',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='sets',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(18, 7, 34, 94165)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 18, 12, 34, 94165, tzinfo=datetime.timezone.utc)),
        ),
    ]
