# Generated by Django 5.1.6 on 2025-02-26 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0038_alter_loggedexercise_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(18, 7, 58, 24861), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 2, 26, 18, 12, 58, 24861, tzinfo=datetime.timezone.utc)),
        ),
    ]
