# Generated by Django 4.2.19 on 2025-03-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0030_alter_otp_expiry_time'),
        ('onboarding', '0039_alter_loggedexercise_time_logged_and_more'),
    ]

    operations = [
    ]
