# Generated by Django 5.1.6 on 2025-02-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0030_alter_otp_expiry_time'),
        ('onboarding', '0039_alter_loggedexercise_time_logged_and_more'),
    ]

    operations = [
    ]
