# Generated by Django 5.1.6 on 2025-03-03 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0040_merge_20250228_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='ex_secondary_muscle',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_secondary_muscle_1',
            field=models.CharField(db_comment='Secondary muscle targeted', default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_secondary_muscle_2',
            field=models.CharField(db_comment='Other Secondary Muscle Targeted', default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='date_logged',
            field=models.DateField(default=datetime.date(2025, 3, 3)),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(19, 5, 7, 24035), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 3, 19, 10, 7, 22793, tzinfo=datetime.timezone.utc)),
        ),
    ]
