# Generated by Django 4.2.19 on 2025-03-02 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0040_merge_20250302_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ex_secondary_muscle',
            new_name='ex_secondary_muscle_1',
        ),
        migrations.AddField(
            model_name='exercise',
            name='ex_secondary_muscle_2',
            field=models.CharField(db_comment='Any other secondary muscles', default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='date_logged',
            field=models.DateField(default=datetime.date(2025, 3, 2)),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(14, 59, 40, 171721), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 2, 15, 4, 40, 171347, tzinfo=datetime.timezone.utc)),
        ),
    ]
