# Generated by Django 5.1.6 on 2025-03-07 17:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0043_alter_loggedexercise_time_logged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='date_logged',
            field=models.DateField(default=datetime.date(2025, 3, 7)),
        ),
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(17, 7, 9, 916748), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 7, 17, 12, 9, 915240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RecommendedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_recommended', models.DateTimeField(default=datetime.datetime(2025, 3, 7, 17, 7, 9, 916748, tzinfo=datetime.timezone.utc))),
                ('good_recommendation', models.BooleanField(default=True)),
                ('sets', models.PositiveSmallIntegerField(default=0, null=True)),
                ('reps', models.PositiveSmallIntegerField(default=0, null=True)),
                ('distance', models.FloatField(default=0.0, null=True)),
                ('distance_units', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], max_length=5, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('equipment_weight', models.JSONField(default=list, null=True)),
                ('equipment_weight_units', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], max_length=2, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
