# Generated by Django 5.1.6 on 2025-03-07 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0044_alter_loggedexercise_date_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(20, 34, 16, 105724), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 7, 20, 39, 16, 104726, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recommendedexercise',
            name='datetime_recommended',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 20, 34, 16, 105724, tzinfo=datetime.timezone.utc)),
        ),
    ]
