# Generated by Django 5.1.6 on 2025-03-07 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0045_alter_loggedexercise_time_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexercise',
            name='time_logged',
            field=models.TimeField(default=datetime.time(21, 3, 22, 641223), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 7, 21, 8, 22, 640198, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recommendedexercise',
            name='datetime_recommended',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 21, 3, 22, 641223, tzinfo=datetime.timezone.utc)),
        ),
    ]
